### PR TITLE
Introduce build reasons & fix caching issues

### LINKED ISSUE #161: Don't use HashCode as Key in IPipelineCache
Currently the HashCode of Build ID strings are used as a key in IPipelineCache.
This cannot work, as a string is theoretically infinitely long while a HashCode is only Int32.

Faulty behavior can already be observed with the DummyPlugin, even though the Build IDs are the same, the HashCode function does not return the same value:
image

The same issue should be present for definitions and branches as well and be fixed within this issue.

### PR DESCRIPTION
**Pull request by BerndNK**
Build reasons are required for #52 
This PR will also close #161

### CODE REVIEW

File: Plugins/BuildNotifications.PluginInterfaces/Builds/BuildReason.cs [hunk 1]
```diff
@@ -0,0 +1,38 @@
+﻿namespace BuildNotifications.PluginInterfaces.Builds
+{
+    /// <summary>
+    /// Describes the reason why a build has been created.
+    /// </summary>
+    public enum BuildReason
```
Comment (TheSylence) [inline Plugins/BuildNotifications.PluginInterfaces/Builds/BuildReason.cs:6]: What is the difference between Unknown and Other?

File: BuildNotifications.Core/Pipeline/Cache/CacheKey.cs [hunk 2]
```diff
@@ -1,8 +1,10 @@
-﻿namespace BuildNotifications.Core.Pipeline.Cache
+﻿using System;
+
+namespace BuildNotifications.Core.Pipeline.Cache
 {
     internal sealed class CacheKey
     {
-        public CacheKey(int providerId, int itemId)
+        public CacheKey(string providerId, string itemId)
```
Comment (TheSylence) [inline BuildNotifications.Core/Pipeline/Cache/CacheKey.cs:7]: Why string as data type for providerId when everytime it is called it is "Guid.ToString()"?

File: Plugins/BuildNotifications.PluginInterfaces/Builds/BuildReason.cs (hunk 1 above)
Comment (BerndNK) [reply Plugins/BuildNotifications.PluginInterfaces/Builds/BuildReason.cs:6]: Other is for reasons plugin may provide that are not supported by BN. Unknown is for the case that plugins cannot provide a reason, or the reason is literally unknown.

If you have a look at [MSDN](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/ff736208(v%3Dvs.120))
you see a couple of examples of build reasons we do not support/need.

File: BuildNotifications.Core/Pipeline/Cache/CacheKey.cs (hunk 2 above)
Comment (BerndNK) [reply BuildNotifications.Core/Pipeline/Cache/CacheKey.cs:7]: I want to keep the option open for other formats of keys. 
Especially for #48 the GUIDs probably won't work anymore.

I used GUID as a quick & easy fix to get a unique string every time. However I can see how it could be better to expose the Id as string within IProject instead of GUID, so you know that it is a string from the outside?

Comment (TheSylence) [reply BuildNotifications.Core/Pipeline/Cache/CacheKey.cs:7]: Okay makes sense
